Add network functions on the DPU side
openshift/dpu-operator pull request #54
Opened 2024-04-22 19:53 UTC by bn222

2024-04-23 18:57 UTC, wizhaoredhat requested changes

2024-04-23 18:57 UTC, wizhaoredhat commented on daemon/sfc-reconciler/sfc.go
> +					Image: image,
We might want to have a PullPolicy = Always for debugging here.

2024-04-23 18:57 UTC, wizhaoredhat commented on daemon/dpudaemon.go
> +		d.log.Info("Starging CNI server")
Indentation and SP "Starting". I think you need to run "go fmt".

2024-04-23 18:57 UTC, wizhaoredhat commented on api/v1/classifierconfig_types.go
> +	Foo string `json:"foo,omitempty"`
Are we missing a real input for this?

2024-04-23 18:57 UTC, wizhaoredhat commented on daemon/dpudaemon.go
> +	go func() {
This implementation does not work:
```package main

import (
	"errors"
	"fmt"
	"time"
)

func something(c chan error) {
	fmt.Println("HELLO1")
	c <- nil
}

func something3(c chan error) {
	fmt.Println("HELLO1")
	time.Sleep(5 * time.Second)
	c <- errors.New("an error")
}

func something2() error {
	c := make(chan error, 1)
	go something(c)
	go something3(c)
	return <-c
}
func main() {
	err := something2()
	fmt.Println(err)
}
```
It does not wait for all the go routines to finish, you need a wait group.

2024-04-23 18:57 UTC, wizhaoredhat commented on daemon/dpudaemon.go
> +	go func() {
Something like this works:
```
package main

import (
	"errors"
	"fmt"
	"sync"
	"time"
)

func test1(wg *sync.WaitGroup, c chan error) {
	defer wg.Done()
	fmt.Println("HELLO1")
	c <- nil
}

func test2(wg *sync.WaitGroup, c chan error) {
	defer wg.Done()
	fmt.Println("HELLO1")
	time.Sleep(5 * time.Second)
	c <- errors.New("an error")
}

func testing() chan error {
	c := make(chan error, 2)
	var wga sync.WaitGroup
	wga.Add(1)
	go test1(&wga, c)
	wga.Add(1)
	go test2(&wga, c)
	wga.Wait()
	close(c)
	return c
}
func main() {
	errors := testing()
	for err := range errors {
		fmt.Println(err)
	}
}
```

2024-04-23 18:57 UTC, wizhaoredhat commented on daemon/hostdaemon.go
> +	go func() {
Same comment as above.

2024-05-23 15:50 UTC, bn222 commented
/override ci/prow/e2e-dpu-operator-tests

2024-05-23 15:53 UTC, bn222 commented
/override ci/prow/e2e-dpu-operator-tests

2024-05-23 16:02 UTC, wizhaoredhat commented on daemon/hostdaemon.go
> +	go func() {
Missing Workgroup?

2024-05-23 16:11 UTC, bn222 commented on daemon/hostdaemon.go
> +	go func() {
yes, thanks.

2024-05-23 16:13 UTC, wizhaoredhat commented on daemon/main.go
> +	return unix.Access(path, unix.W_OK) == nil
This does not work. I tried it before.

2024-05-23 16:13 UTC, wizhaoredhat commented on daemon/main.go
> +	return unix.Access(path, unix.W_OK) == nil
I think I removed it priorly.

2024-05-27 08:47 UTC, bn222 commented
/override ci/prow/e2e-dpu-operator-tests

2024-05-27 11:06 UTC, bn222 commented
/override ci/prow/e2e-dpu-operator-tests

2024-05-27 14:35 UTC, wizhaoredhat commented
/lgtm

2024-05-27 14:39 UTC, merged